### ISSUE TITLE
Desktop Runtime not working on MacOS

### ISSUE THREAD

**Issue by appcellphone** [PeytonPlayz595/Shadow-4.0#3]
@PeytonPlayz595 

Hello hello, please help me, I downloaded a zip file on my macOS silicon chip, then I did chmod +x for gradlew and ran ./gradlew runclient but I still got the 2 errors below. Thank you for sharing this amazing project!

```
user_name@Name-MacBook-Pro Shadow-4.0-main % ./gradlew runclient

> Task :compileEaglerJava
/Users/user_name/Downloads/Shadow-4.0-main/src/main/java/net/PeytonPlayz585/shadow/TextureUtils.java:6: error: package org.teavm.jso.typedarrays does not exist
import org.teavm.jso.typedarrays.ArrayBuffer;
                                ^
/Users/user_name/Downloads/Shadow-4.0-main/src/main/java/net/PeytonPlayz585/shadow/TextureUtils.java:7: error: package org.teavm.jso.typedarrays does not exist
import org.teavm.jso.typedarrays.DataView;
```

**Comment by PeytonPlayz595** [comment]
> @PeytonPlayz595
> 
> Hello hello, please help me, I downloaded a zip file on my macOS silicon chip, then I did chmod +x for gradlew and ran ./gradlew runclient but I still got the 2 errors below. Thank you for sharing this amazing project!
> 
> ```
> user_name@Name-MacBook-Pro Shadow-4.0-main % ./gradlew runclient
> 
> > Task :compileEaglerJava
> /Users/user_name/Downloads/Shadow-4.0-main/src/main/java/net/PeytonPlayz585/shadow/TextureUtils.java:6: error: package org.teavm.jso.typedarrays does not exist
> import org.teavm.jso.typedarrays.ArrayBuffer;
>                                 ^
> /Users/user_name/Downloads/Shadow-4.0-main/src/main/java/net/PeytonPlayz585/shadow/TextureUtils.java:7: error: package org.teavm.jso.typedarrays does not exist
> import org.teavm.jso.typedarrays.DataView;
> ```

You're gonna have to redownload the repo, I accidentally left some imports in the code for the browser runtime, and those API's are not supported in the desktop runtime. I fixed it in [this commit](https://github.com/PeytonPlayz595/Shadow-4.0/commit/d19de81370b5cf97c109f5a05aead58ba22c5576) so you must be using a slightly outdated version.

**Comment by appcellphone** [comment]
@PeytonPlayz595
Yay Thank you so much! The Task :compileEaglerJava now done but the client do not show the window, here the latest log i see in the console:
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 warnings
<=========----> 75% EXECUTING [1m 46s]
> :runclient

```

**Comment by PeytonPlayz595** [comment]
> @PeytonPlayz595 Yay Thank you so much! The Task :compileEaglerJava now done but the client do not show the window, here the latest log i see in the console:
> 
> ```
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 5 warnings
> <=========----> 75% EXECUTING [1m 46s]
> > :runclient
> ```

When I run it a pop up appears that says launch renderdoc and continue (optional) and you just have to click ok

**Comment by appcellphone** [comment]
@PeytonPlayz595 
How can we active or accept the renderdoc because I try "Show all windows" in the terminal but nothing happen or showing:
<img width="644" alt="image" src="https://github.com/PeytonPlayz595/Shadow-4.0/assets/117508478/94468b01-320a-4c06-bd75-2f9e50d171dd">

**Comment by PeytonPlayz595** [comment]
@appcellphone I've never used MacOS, are you able to provide a screen recording showing how you run it?

**Comment by PeytonPlayz595** [comment]
Ik in the build.gradle there is this code, I'm not sure what it does, I'll have to ask radman since he made it but it has something to do with Mac:
```kotlin
if (System.getProperty("os.name").toLowerCase().contains("mac")) {
    jvmArgs '-XstartOnFirstThread'
}
```
What happens when you remove that code?

**Comment by radmanplays** [comment]
> Ik in the build.gradle there is this code, I'm not sure what it does, I'll have to ask radman since he made it but it has something to do with Mac:
> 
> ```kotlin
> if (System.getProperty("os.name").toLowerCase().contains("mac")) {
>     jvmArgs '-XstartOnFirstThread'
> }
> ```
> 
> What happens when you remove that code?

-XstartOnFirstThread is a vm arg required for mac users to run the client as mentioned here: https://stackoverflow.com/questions/28149634/what-does-the-xstartonfirstthread-vm-argument-do-mean
and here: 
https://www.lwjgl.org/guide

that code in build.gradle detects if the user is using macOS and if yes it adds the vm arg "-XstartOnFirstThread"

its used in mcpReborn's build.gradle too

**Comment by PeytonPlayz595** [comment]
Oh, when I googled it I couldn't find anything about it.

**Comment by appcellphone** [comment]
@PeytonPlayz595 
I can setup the debug in clion and i see that it stop at: double r = win.getDevicePixelRatio();

<img width="1704" alt="image" src="https://github.com/PeytonPlayz595/Shadow-4.0/assets/117508478/f6fb4c70-7170-464b-89e8-26cd309adb24">

<img width="1622" alt="image" src="https://github.com/PeytonPlayz595/Shadow-4.0/assets/117508478/0e9b749c-7572-4f09-9d0d-3d942693e850">

**Comment by appcellphone** [comment]
And from the code, we can hide the renderdoc confirm by adding args 'hide-renderdoc'
```
tasks.register('runclient', JavaExec) {
    classpath = sourceSets.eagler.compileClasspath
    group = "ShadowClient"
    description = "Runs the client"
    classpath sourceSets.eagler.runtimeClasspath
    if (System.getProperty("os.name").toLowerCase().contains("mac")) {
        jvmArgs '-XstartOnFirstThread','-Dorg.lwjgl.util.Debug=true', '-Dorg.lwjgl.util.DebugLoader=true'
    }
    if (project.hasProperty("appArgs")) {
        args Eval.me(project.appArgs)
    }
    args 'hide-renderdoc'
    workingDir "./desktopRuntime"
    main 'net.lax1dude.eaglercraft.v1_8.internal.lwjgl.MainClass'
}
```

**Comment by PeytonPlayz595** [comment]
> @PeytonPlayz595 I can setup the debug in clion and i see that it stop at: double r = win.getDevicePixelRatio();
> 
> <img alt="image" width="1704" src="https://private-user-images.githubusercontent.com/117508478/324312435-f6fb4c70-7170-464b-89e8-26cd309adb24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzU5ODQsIm5iZiI6MTcxMzgzNTY4NCwicGF0aCI6Ii8xMTc1MDg0NzgvMzI0MzEyNDM1LWY2ZmI0YzcwLTcxNzAtNDY0Yi04OWU4LTI2Y2QzMDlhZGIyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwMTI4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDQ5MGRkNzkyYTEzNDAyN2VhZWMxZGEwZjExYTljZTFkY2E3NmY4OGZkYTZjYTRkNTNjYzhmOTMxOTA0YjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7e0zoLYUIQiKEWdKuaNLUPv39KPRJCPd0oJ-4xMrsNI"> <img alt="image" width="1622" src="https://private-user-images.githubusercontent.com/117508478/324312528-0e9b749c-7572-4f09-9d0d-3d942693e850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzU5ODQsIm5iZiI6MTcxMzgzNTY4NCwicGF0aCI6Ii8xMTc1MDg0NzgvMzI0MzEyNTI4LTBlOWI3NDljLTc1NzItNGYwOS05ZDBkLTNkOTQyNjkzZTg1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwMTI4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTgxZDNiNmE5ZGY5NGI1MDBhOTE1OGVjYTRiOGFiYmFkMDBhNTBlZDBkYzgyMzVkOTI2NWI3MzVjOGYyZjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ANzo1J5KJBjjOnTiQglCAKIVxtHG_FMYLg_EWbR18B8">

That's the code for the browser runtime, for the desktop runtime the classpath needs to be set to `src/lwjgl/java` instead of `src/teavm/java`

**Comment by appcellphone** [comment]
@PeytonPlayz595 
Yay, thank you for patiently supporting me, I really appreciate it! I have deleted the teavm code so that PlatformRuntime is selected from src/lwjgl/java. And when debugging, the program stops at: windowHandle = glfwCreateWindow(windowWidth, windowHeight, "Eaglercraft Desktop Runtime", 0l, 0l);
<img width="1701" alt="image" src="https://github.com/PeytonPlayz595/Shadow-4.0/assets/117508478/ebfe070f-3048-4f74-9b28-a9b048bdd5d0">

**Comment by radmanplays** [comment]
> @PeytonPlayz595 Yay, thank you for patiently supporting me, I really appreciate it! I have deleted the teavm code so that PlatformRuntime is selected from src/lwjgl/java. And when debugging, the program stops at: windowHandle = glfwCreateWindow(windowWidth, windowHeight, "Eaglercraft Desktop Runtime", 0l, 0l); <img alt="image" width="1701" src="https://private-user-images.githubusercontent.com/117508478/324671098-ebfe070f-3048-4f74-9b28-a9b048bdd5d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjcxMTcsIm5iZiI6MTcxMzg2NjgxNywicGF0aCI6Ii8xMTc1MDg0NzgvMzI0NjcxMDk4LWViZmUwNzBmLTMwNDgtNGY3NC05YjI4LWE5YjA0OGJkZDVkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMDA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzc5ODFkMDMyMjg1NWVkMGNjYTMzOTg2NmY1ZDI0N2NhZjQ3YjljODQ4ZTUyMDkzYjUzYjc5ZWQ1OTNmZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qoLWjFUTSmTEmk9tgEQ2_Z6cyMadDiNxEs0dgzuZdUw">

bro, just download the repo again, go to the src folder and ONLY DELETE THE FOLDER CALLED "teavm" and DO NOT DELETE "lwjgl"

**Comment by appcellphone** [comment]
@radmanplays Thank you so much, after attempting to delete the folder in src, I still encountered the program halting. I tried to find ways to display a window if any, but no window or dialog appeared.
```
user_name@User-MacBook-Pro Shadow-4.0 % ./gradlew runclient

> Task :runclient
[09:24:40+743][main/INFO][EagRuntime]: Version: EagRuntimeX 1.0
[09:24:40+746][main/INFO][RuntimeLWJGL3]: Starting Desktop Runtime...
[LWJGL] Version: 3.3.3+5
         OS: Mac OS X v14.4.1
        JRE: macOS aarch64 21.0.1
        JVM: OpenJDK 64-Bit Server VM v21.0.1 by Homebrew
[LWJGL] Loading JNI library: lwjgl
        Module: org.lwjgl
        macos/arm64/org/lwjgl/liblwjgl.dylib not found in java.library.path=/Users/user_name/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
        Loaded from java.library.path: ./liblwjgl.dylib
[LWJGL] Loading library: glfw
        Module: org.lwjgl.glfw
        Loaded from java.library.path: ./libglfw.dylib
[LWJGL] Loading library: objc
        Module: org.lwjgl
[LWJGL] Loading library: jemalloc
        Module: org.lwjgl.jemalloc
        Loaded from java.library.path: ./libjemalloc.dylib
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Java 9 text decoding enabled
        Loaded from system paths: /usr/lib/libobjc.A.dylib
[LWJGL] Java 10 multiplyHigh enabled
[09:24:40+828][main/INFO][RuntimeLWJGL3]: GLFW Version: 3.4.0 Cocoa NSGL Null EGL OSMesa monotonic dynamic
[LWJGL] Java 9 check intrinsics enabled
<=========----> 75% EXECUTING [20s]
> :runclient

```
my java version

```
java --version
openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)
```

**Comment by PeytonPlayz595** [comment]
Try setting up the project in eclipse and running the `eaglercraftDebugRuntime.launch` configuration and see if it'll run like that,

**Comment by PeytonPlayz595** [comment]
@orionzleon @appcellphone 
You will have to use the browser version, it doesn't have any natives for MacOS

![Screenshot (470)](https://github.com/PeytonPlayz595/Shadow-4.0/assets/106421860/47f44821-3618-455b-a149-4da7b4731e49)

**Comment by appcellphone** [comment]
@PeytonPlayz595 
Thank you for the incredibly useful information! What operating system do you normally use to code and debug in Eclipse? If I use the browser version, does that mean I will code in Java and then build it into JavaScript and test it on the web?

**Comment by PeytonPlayz595** [comment]
> @PeytonPlayz595 Thank you for the incredibly useful information! What operating system do you normally use to code and debug in Eclipse? If I use the browser version, does that mean I will code in Java and then build it into JavaScript and test it on the web?

I use Windows 10, and yes, you program in java and run `gradlew generatejavascript` to build the JavaScript client, the directory for the web client is `/javascript`

**Comment by appcellphone** [comment]
Yay! Thank you so much! I will trying that way!
